# Generated by Django 4.1 on 2022-08-08 16:27

import core.models
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_principal_cac_alter_principal_id_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='principal',
            name='CAC',
            field=models.FileField(default='default_id.png', upload_to=core.models.get_credentials_path, validators=[core.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'pdf', 'png'])]),
        ),
        migrations.AlterField(
            model_name='principal',
            name='id_card',
            field=models.FileField(default='default_id.png', upload_to=core.models.get_credentials_path, validators=[core.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'pdf', 'png'])]),
        ),
        migrations.AlterField(
            model_name='principal',
            name='letter',
            field=models.FileField(default='default_id.png', upload_to=core.models.get_credentials_path, validators=[core.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'pdf', 'png'])]),
        ),
        migrations.AlterField(
            model_name='school',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to=core.models.get_school_logo_path),
        ),
    ]
