# Generated by Django 4.1 on 2022-08-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220808_0026'),
        ('core', '0003_principal_verification_alter_principal_cac_and_more'),
    ]

    operations = [
    ]
