# Generated by Django 4.1 on 2022-08-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20220809_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
