# Generated by Django 4.0.5 on 2022-08-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20220809_1053'),
        ('core', '0005_alter_principal_gender'),
    ]

    operations = [
    ]
