# Generated by Django 4.1 on 2022-08-10 10:59

from django.db import migrations, models
import info_hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('info_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, validators=[info_hub.models.validate_newsletter_instance]),
        ),
    ]
