# Generated by Django 4.1 on 2022-09-26 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info_hub", "0002_alter_newsletter_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "mp4", "mkv"]
                    )
                ],
            ),
        ),
    ]
