# Generated by Django 4.1 on 2022-08-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydebtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='mydebtors.student'),
        ),
    ]
