# Generated by Django 4.1 on 2022-08-08 16:27

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mydebtors.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mydebtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('proof', models.FileField(blank=True, null=True, upload_to=mydebtors.models.get_complaint_path, validators=[core.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'pdf', 'png'])])),
                ('status', models.CharField(choices=[('cleared', 'cleared'), ('pending', 'pending')], default='pending', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=10)),
                ('term', models.CharField(max_length=20)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('outstanding_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('resolved', 'resolved')], default='active', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('state', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=550)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='-', max_length=550),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.ImageField(default='default.jpg', upload_to=mydebtors.models.get_passport_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_number',
            field=models.CharField(default=mydebtors.models.reg_number_generator, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='mydebtors.student'),
        ),
        migrations.AddField(
            model_name='debt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='mydebtors.student'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='mydebtors.debt'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
