# Generated by Django 4.1 on 2022-09-29 11:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mydebtors", "0003_contact_email"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="ContactDetails",
        ),
    ]
