# Generated by Django 4.1 on 2022-08-10 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydebtors', '0004_alter_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='school',
        ),
    ]
