# Generated by Django 4.1 on 2022-08-12 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_nin'),
        ('mydebtors', '0005_rename_user_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.school'),
            preserve_default=False,
        ),
    ]
