# Generated by Django 4.1 on 2022-08-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydebtors', '0006_complaint_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='NIN',
            field=models.CharField(default='123', max_length=11),
            preserve_default=False,
        ),
    ]
