# Generated by Django 4.1 on 2022-08-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_nin'),
        ('mydebtors', '0007_sponsor_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='core.school'),
            preserve_default=False,
        ),
    ]
